package ua.com.foxminded.sqljdbcschool.model;

public enum LastNameEnum {
    TSYGANKOV, GARMASH, POPOV, SUPRIHA, SYDORCHUK, BUSHCAN, MYKOLENKO, BUIALSKYI, ZABARNYI, KARAVAIEV, LEDNEV,
    SHAPARENKO, BURDA, SHABANOB, NESHCHERET, TYMCHYK, SHEPELEV, ANDRIYEVSKYI, RUSYN, BESEDIN;
}
